function [] = plottraj(trajectory,cmap)

% Sebastian Jaramillo-Riveri
% November, 2018

    ntrajcs = size(trajectory,1);
    colors  = eval([cmap,'(ntrajcs-1)']);

    coorplots = [1,2;...
                 1,3;...
                 3,2];
    titles    = {'X v/s Y','X v/s Z','Z v/s Y'};
    xlegends  = {'X','X','Z'};
    ylegends  = {'Y','Z','Y'};
    fsize = 12;
    lw = 1;
    
    for i = 1:3
        subplot(1,4,i); hold on;
        c1 = coorplots(i,1);
        c2 = coorplots(i,2);
        for n = 1:(ntrajcs-1)
            plot([trajectory(n,c1),trajectory(n+1,c1)],...
                 [trajectory(n,c2),trajectory(n+1,c2)],...
                 '-',...
                 'LineWidth',lw,...
                 'Color',colors(n,:));
            plot([trajectory(n,c1),trajectory(n+1,c1)],...
                 [trajectory(n,c2),trajectory(n+1,c2)],...
                 '.',...
                 'LineWidth',lw,...
                 'Color',colors(n,:));
        end
        figlabels('title',['\bf ',titles{i}],...
                  'xlabel',xlegends{i},...
                  'ylabel',ylegends{i},...
                  'fsize',fsize);
    end
    
    subplot(1,4,4); hold on;
    for n = 1:(ntrajcs-1)
        plot3(trajectory([n,n+1],1),trajectory([n,n+1],2),trajectory([n,n+1],3),...
              '-',...
              'LineWidth',lw,...
              'Color',colors(n,:));
        plot3(trajectory([n,n+1],1),trajectory([n,n+1],2),trajectory([n,n+1],3),...
              '.',...
              'LineWidth',lw,...
              'Color',colors(n,:));
    end
    view([45,45]);
    xlabel('X','Interpreter','latex','FontSize',fsize,'Color','black');
    ylabel('Y','Interpreter','latex','FontSize',fsize,'Color','black');
    zlabel('Z','Interpreter','latex','FontSize',fsize,'Color','black');
    title('\bf 3D','Interpreter','latex','FontSize',fsize,'Color','black');
    
end